[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts-upgradeable=node_modules/@openzeppelin/contracts-upgradeable',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
